
#line 3 "lex.expPar.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer expPar_create_buffer
#define yy_delete_buffer expPar_delete_buffer
#define yy_scan_buffer expPar_scan_buffer
#define yy_scan_string expPar_scan_string
#define yy_scan_bytes expPar_scan_bytes
#define yy_init_buffer expPar_init_buffer
#define yy_flush_buffer expPar_flush_buffer
#define yy_load_buffer_state expPar_load_buffer_state
#define yy_switch_to_buffer expPar_switch_to_buffer
#define yypush_buffer_state expParpush_buffer_state
#define yypop_buffer_state expParpop_buffer_state
#define yyensure_buffer_stack expParensure_buffer_stack
#define yy_flex_debug expPar_flex_debug
#define yyin expParin
#define yyleng expParleng
#define yylex expParlex
#define yylineno expParlineno
#define yyout expParout
#define yyrestart expParrestart
#define yytext expPartext
#define yywrap expParwrap
#define yyalloc expParalloc
#define yyrealloc expParrealloc
#define yyfree expParfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define expPar_create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer expPar_create_buffer
#endif

#ifdef yy_delete_buffer
#define expPar_delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer expPar_delete_buffer
#endif

#ifdef yy_scan_buffer
#define expPar_scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer expPar_scan_buffer
#endif

#ifdef yy_scan_string
#define expPar_scan_string_ALREADY_DEFINED
#else
#define yy_scan_string expPar_scan_string
#endif

#ifdef yy_scan_bytes
#define expPar_scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes expPar_scan_bytes
#endif

#ifdef yy_init_buffer
#define expPar_init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer expPar_init_buffer
#endif

#ifdef yy_flush_buffer
#define expPar_flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer expPar_flush_buffer
#endif

#ifdef yy_load_buffer_state
#define expPar_load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state expPar_load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define expPar_switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer expPar_switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define expParpush_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state expParpush_buffer_state
#endif

#ifdef yypop_buffer_state
#define expParpop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state expParpop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define expParensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack expParensure_buffer_stack
#endif

#ifdef yylex
#define expParlex_ALREADY_DEFINED
#else
#define yylex expParlex
#endif

#ifdef yyrestart
#define expParrestart_ALREADY_DEFINED
#else
#define yyrestart expParrestart
#endif

#ifdef yylex_init
#define expParlex_init_ALREADY_DEFINED
#else
#define yylex_init expParlex_init
#endif

#ifdef yylex_init_extra
#define expParlex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra expParlex_init_extra
#endif

#ifdef yylex_destroy
#define expParlex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy expParlex_destroy
#endif

#ifdef yyget_debug
#define expParget_debug_ALREADY_DEFINED
#else
#define yyget_debug expParget_debug
#endif

#ifdef yyset_debug
#define expParset_debug_ALREADY_DEFINED
#else
#define yyset_debug expParset_debug
#endif

#ifdef yyget_extra
#define expParget_extra_ALREADY_DEFINED
#else
#define yyget_extra expParget_extra
#endif

#ifdef yyset_extra
#define expParset_extra_ALREADY_DEFINED
#else
#define yyset_extra expParset_extra
#endif

#ifdef yyget_in
#define expParget_in_ALREADY_DEFINED
#else
#define yyget_in expParget_in
#endif

#ifdef yyset_in
#define expParset_in_ALREADY_DEFINED
#else
#define yyset_in expParset_in
#endif

#ifdef yyget_out
#define expParget_out_ALREADY_DEFINED
#else
#define yyget_out expParget_out
#endif

#ifdef yyset_out
#define expParset_out_ALREADY_DEFINED
#else
#define yyset_out expParset_out
#endif

#ifdef yyget_leng
#define expParget_leng_ALREADY_DEFINED
#else
#define yyget_leng expParget_leng
#endif

#ifdef yyget_text
#define expParget_text_ALREADY_DEFINED
#else
#define yyget_text expParget_text
#endif

#ifdef yyget_lineno
#define expParget_lineno_ALREADY_DEFINED
#else
#define yyget_lineno expParget_lineno
#endif

#ifdef yyset_lineno
#define expParset_lineno_ALREADY_DEFINED
#else
#define yyset_lineno expParset_lineno
#endif

#ifdef yywrap
#define expParwrap_ALREADY_DEFINED
#else
#define yywrap expParwrap
#endif

#ifdef yyalloc
#define expParalloc_ALREADY_DEFINED
#else
#define yyalloc expParalloc
#endif

#ifdef yyrealloc
#define expParrealloc_ALREADY_DEFINED
#else
#define yyrealloc expParrealloc
#endif

#ifdef yyfree
#define expParfree_ALREADY_DEFINED
#else
#define yyfree expParfree
#endif

#ifdef yytext
#define expPartext_ALREADY_DEFINED
#else
#define yytext expPartext
#endif

#ifdef yyleng
#define expParleng_ALREADY_DEFINED
#else
#define yyleng expParleng
#endif

#ifdef yyin
#define expParin_ALREADY_DEFINED
#else
#define yyin expParin
#endif

#ifdef yyout
#define expParout_ALREADY_DEFINED
#else
#define yyout expParout
#endif

#ifdef yy_flex_debug
#define expPar_flex_debug_ALREADY_DEFINED
#else
#define yy_flex_debug expPar_flex_debug
#endif

#ifdef yylineno
#define expParlineno_ALREADY_DEFINED
#else
#define yylineno expParlineno
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 39
#define YY_END_OF_BUFFER 40
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[352] =
    {   0,
        1,    1,   38,   38,   40,   39,    1,   33,   39,   35,
       31,   32,   35,   35,   35,   35,   35,   35,   35,   35,
        3,    4,    5,    6,   36,   38,   37,    1,   34,   35,
        0,   31,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   36,   38,   30,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       18,   35,   35,   35,   35,   35,   35,   35,   35,   35,

       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   17,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   29,   35,   35,   35,   25,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   28,   35,   35,
       35,   35,   35,   35,   35,   35,   24,    7,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,

       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   10,
       35,   27,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,    2,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   26,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   20,    9,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,    8,   35,

       35,   35,   35,   35,   14,   12,   35,   35,   35,   35,
       35,   22,   35,   35,   35,   35,   35,   35,   35,   15,
       35,   35,   35,   35,   35,   35,   21,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   19,   35,
       11,   35,   35,   16,   23,   35,   35,   35,   35,   13,
        0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    4,    5,    6,    7,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    9,    1,    1,
        1,   10,    1,    1,   11,   12,   13,   14,   15,   16,
       17,   18,   19,    7,    7,   20,   21,   22,   23,   24,
        7,   25,   26,   27,   28,   29,    7,   30,   31,   32,
       33,    1,   34,    1,   35,    1,   36,   37,   38,   39,

       40,   41,   42,   43,   44,    7,    7,   45,   46,   47,
       48,   49,    7,   50,   51,   52,   53,   54,    7,   55,
       56,   57,   58,    1,   59,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[60] =
    {   0,
        1,    1,    2,    1,    1,    3,    3,    3,    1,    1,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    1,    1,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    1,    1
    } ;

static const flex_int16_t yy_base[355] =
    {   0,
        0,    0,   58,   60,  694,  695,   62,  695,  683,    0,
       60,  695,   47,   41,   50,   62,   63,   55,   61,   64,
      695,  695,  695,  695,    0,   81,  695,   83,  695,    0,
      684,   81,   56,   73,   71,   79,   76,   73,   87,   82,
       96,   88,   91,   98,  110,    0,  120,  683,  109,  111,
       99,  109,  655,  103,  114,  118,  114,  121,  125,  116,
      128,  118,  125,  132,  120,  654,  139,  143,  150,  653,
      147,  145,  157,  144,  159,  652,  156,  159,  152,  151,
      155,  158,  162,  162,  161,  167,  166,  170,  166,  175,
        0,  172,  176,  180,  183,  191,  197,  196,  192,  198,

      205,  209,  651,  650,  207,  200,  213,  212,  205,  212,
      209,  213,  216,  225,  231,  231,  221,  649,  224,  234,
      236,  241,  235,    0,  251,  241,  248,  258,  648,  255,
      255,  265,  255,  263,  263,  269,  270,  260,  265,  262,
      264,  270,  647,  278,  275,  277,  646,  278,  645,  278,
      644,  284,  283,    0,  289,  292,  295,  296,  304,  299,
      300,  312,  302,  643,  305,  306,  319,  320,  322,  315,
      315,  321,  336,  329,  335,  332,  340,    0,  338,  346,
      339,  347,  356,  352,  350,  356,    0,    0,  351,  356,
      354,  358,  367,  642,  371,  368,  365,  368,  368,  368,

      380,  374,  378,  641,  382,  398,  395,  396,  389,  392,
      392,  398,  412,  402,  407,  408,  415,  414,  406,    0,
      410,    0,  412,  422,  426,  414,  420,  432,  424,  426,
      419,  443,  439,  445,  435,    0,  639,  629,  443,  437,
      458,  448,  459,  456,  450,  627,  452,    0,  459,  459,
      457,  626,  462,  465,  466,  476,  465,  477,  625,  471,
      471,  475,  472,  488,  478,  483,  483,  489,  484,  503,
      507,  513,  624,  506,  507,  503,    0,  517,  504,  515,
      516,  513,  524,  514,  509,  515,  532,  524,  521,  535,
      536,  530,  545,  542,  547,  533,  545,  545,    0,  546,

      560,  557,  552,  546,    0,    0,  568,  623,  553,  556,
      568,  564,  575,  570,  565,  574,  583,  569,  587,    0,
      582,  586,  587,  584,  601,  589,    0,  613,  598,  602,
      604,  614,  605,  601,  605,  603,  609,  612,    0,  610,
        0,  612,  623,    0,    0,  616,  631,  616,  629,    0,
      695,  669,  644,  672
    } ;

static const flex_int16_t yy_def[355] =
    {   0,
      351,    1,  352,  352,  351,  351,  351,  351,  351,  353,
      351,  351,  353,  353,  353,  353,  353,  353,  353,  353,
      351,  351,  351,  351,  354,  351,  351,  351,  351,  353,
      351,  351,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  354,  351,  351,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,

      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,

      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,

      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
        0,  351,  351,  351
    } ;

static const flex_int16_t yy_nxt[755] =
    {   0,
        6,    7,    7,    8,    9,   10,   10,   11,   12,    6,
       10,   10,   13,   10,   14,   10,   10,   10,   15,   10,
       16,   17,   10,   18,   19,   20,   10,   10,   10,   10,
       10,   10,   21,   22,   10,   10,   10,   13,   10,   14,
       10,   10,   10,   15,   10,   16,   17,   10,   18,   19,
       20,   10,   10,   10,   10,   10,   10,   23,   24,   26,
       26,   26,   26,   28,   28,   31,   27,   32,   27,   33,
       34,   35,   36,   38,   40,   42,   43,   49,   44,   41,
       37,   45,   47,   47,   28,   28,   31,   50,   32,   51,
       39,   52,   54,   55,   33,   34,   35,   36,   38,   40,

       42,   43,   49,   44,   41,   37,   45,   56,   53,   57,
       58,   59,   50,   60,   51,   39,   52,   54,   55,   61,
       62,   47,   47,   65,   63,   66,   67,   69,   70,   71,
       72,   73,   56,   53,   57,   58,   59,   64,   60,   74,
       75,   76,   77,   78,   61,   62,   79,   80,   65,   63,
       66,   67,   69,   70,   71,   72,   73,   82,   83,   84,
       85,   87,   64,   88,   74,   75,   76,   77,   78,   89,
       90,   79,   80,   91,   93,   94,   95,   96,   97,   98,
       99,  100,   82,   83,   84,   85,   87,  101,   88,  102,
      103,  104,  105,  106,   89,   90,  107,  108,   91,   93,

       94,   95,   96,   97,   98,   99,  100,  109,  110,  111,
      114,  112,  101,  115,  102,  103,  104,  105,  106,  113,
      116,  107,  108,  117,  118,  121,  122,  123,  124,  125,
      126,  127,  109,  110,  111,  114,  112,  128,  115,  129,
      130,  131,  132,  133,  113,  116,  135,  136,  117,  118,
      121,  122,  123,  124,  125,  126,  127,  137,  138,  139,
      140,  141,  128,  142,  129,  130,  131,  132,  133,  143,
      144,  135,  136,  146,  147,  148,  149,  150,  151,  152,
      153,  154,  137,  138,  139,  140,  141,  155,  142,  156,
      157,  158,  160,  161,  143,  144,  162,  164,  146,  147,

      148,  149,  150,  151,  152,  153,  154,  166,  168,  169,
      170,  171,  155,  172,  156,  157,  158,  160,  161,  173,
      176,  162,  164,  174,  175,  177,  178,  179,  181,  183,
      186,  182,  166,  168,  169,  170,  171,  184,  172,  187,
      188,  189,  185,  190,  173,  176,  191,  192,  174,  175,
      177,  178,  179,  181,  183,  186,  182,  193,  194,  195,
      196,  197,  184,  198,  187,  188,  189,  185,  190,  199,
      200,  191,  192,  201,  202,  203,  204,  205,  206,  207,
      208,  210,  193,  194,  195,  196,  197,  211,  198,  212,
      213,  214,  215,  216,  199,  200,  217,  218,  201,  202,

      203,  204,  205,  206,  207,  208,  210,  220,  221,  222,
      223,  224,  211,  225,  212,  213,  214,  215,  216,  226,
      227,  217,  218,  228,  229,  230,  231,  232,  233,  234,
      235,  236,  220,  221,  222,  223,  224,  237,  225,  238,
      239,  240,  241,  242,  226,  227,  243,  244,  228,  229,
      230,  231,  232,  233,  234,  235,  236,  245,  246,  247,
      248,  251,  237,  252,  238,  239,  240,  241,  242,  253,
      254,  243,  244,  255,  256,  257,  259,  260,  261,  262,
      264,  265,  245,  246,  247,  248,  251,  266,  252,  267,
      268,  269,  271,  272,  253,  254,  273,  274,  255,  256,

      257,  259,  260,  261,  262,  264,  265,  275,  276,  277,
      278,  279,  266,  280,  267,  268,  269,  271,  272,  281,
      282,  273,  274,  283,  285,  286,  287,  288,  289,  290,
      291,  292,  275,  276,  277,  278,  279,  293,  280,  294,
      295,  296,  297,  298,  281,  282,  299,  300,  283,  285,
      286,  287,  288,  289,  290,  291,  292,  301,  302,  303,
      304,  305,  293,  306,  294,  295,  296,  297,  298,  307,
      308,  299,  300,  309,  310,  311,  312,  313,  314,  316,
      317,  318,  301,  302,  303,  304,  305,  319,  306,  320,
      321,  322,  323,  324,  307,  308,  325,  326,  309,  310,

      311,  312,  313,  314,  316,  317,  318,  327,  328,  329,
      330,  331,  319,  332,  320,  321,  322,  323,  324,  334,
      335,  325,  326,  336,  337,  338,  339,  340,  341,  342,
      343,  344,  327,  328,  329,  330,  331,  345,  332,  346,
      347,  348,  349,  350,  334,  335,   30,  333,  336,  337,
      338,  339,  340,  341,  342,  343,  344,  315,  284,  270,
      263,  258,  345,  250,  346,  347,  348,  349,  350,   25,
       25,   25,   46,  249,   46,  219,  209,  180,  167,  165,
      163,  159,  145,  134,  120,  119,   92,   86,   81,   68,
       48,   48,   29,  351,    5,  351,  351,  351,  351,  351,

      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351
    } ;

static const flex_int16_t yy_chk[755] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        3,    4,    4,    7,    7,   11,    3,   11,    4,   13,
       14,   15,   16,   17,   18,   19,   20,   33,   20,   18,
       16,   20,   26,   26,   28,   28,   32,   34,   32,   35,
       17,   36,   37,   38,   13,   14,   15,   16,   17,   18,

       19,   20,   33,   20,   18,   16,   20,   39,   36,   40,
       41,   42,   34,   43,   35,   17,   36,   37,   38,   44,
       45,   47,   47,   50,   49,   51,   52,   54,   55,   56,
       57,   58,   39,   36,   40,   41,   42,   49,   43,   59,
       60,   61,   62,   63,   44,   45,   64,   65,   50,   49,
       51,   52,   54,   55,   56,   57,   58,   67,   68,   68,
       69,   71,   49,   72,   59,   60,   61,   62,   63,   73,
       74,   64,   65,   75,   77,   78,   79,   80,   81,   82,
       83,   84,   67,   68,   68,   69,   71,   85,   72,   86,
       87,   88,   89,   90,   73,   74,   92,   93,   75,   77,

       78,   79,   80,   81,   82,   83,   84,   94,   95,   96,
       98,   97,   85,   99,   86,   87,   88,   89,   90,   97,
      100,   92,   93,  101,  102,  105,  106,  107,  108,  109,
      110,  111,   94,   95,   96,   98,   97,  112,   99,  113,
      114,  115,  116,  117,   97,  100,  119,  119,  101,  102,
      105,  106,  107,  108,  109,  110,  111,  120,  121,  122,
      123,  125,  112,  126,  113,  114,  115,  116,  117,  127,
      128,  119,  119,  130,  131,  132,  133,  134,  135,  136,
      137,  138,  120,  121,  122,  123,  125,  139,  126,  140,
      141,  142,  144,  145,  127,  128,  146,  148,  130,  131,

      132,  133,  134,  135,  136,  137,  138,  150,  152,  153,
      155,  156,  139,  157,  140,  141,  142,  144,  145,  158,
      160,  146,  148,  159,  159,  161,  162,  163,  165,  166,
      168,  165,  150,  152,  153,  155,  156,  167,  157,  169,
      170,  171,  167,  172,  158,  160,  173,  174,  159,  159,
      161,  162,  163,  165,  166,  168,  165,  175,  176,  177,
      179,  180,  167,  181,  169,  170,  171,  167,  172,  182,
      183,  173,  174,  184,  185,  186,  189,  190,  191,  192,
      193,  195,  175,  176,  177,  179,  180,  196,  181,  197,
      198,  199,  200,  201,  182,  183,  202,  203,  184,  185,

      186,  189,  190,  191,  192,  193,  195,  205,  206,  207,
      208,  209,  196,  210,  197,  198,  199,  200,  201,  211,
      212,  202,  203,  213,  214,  215,  216,  217,  218,  219,
      221,  223,  205,  206,  207,  208,  209,  224,  210,  225,
      226,  227,  228,  229,  211,  212,  230,  231,  213,  214,
      215,  216,  217,  218,  219,  221,  223,  232,  233,  234,
      235,  239,  224,  240,  225,  226,  227,  228,  229,  241,
      242,  230,  231,  243,  244,  245,  247,  249,  250,  251,
      253,  254,  232,  233,  234,  235,  239,  255,  240,  256,
      257,  258,  260,  261,  241,  242,  262,  263,  243,  244,

      245,  247,  249,  250,  251,  253,  254,  264,  265,  266,
      267,  268,  255,  269,  256,  257,  258,  260,  261,  270,
      271,  262,  263,  272,  274,  275,  276,  278,  279,  280,
      281,  282,  264,  265,  266,  267,  268,  283,  269,  284,
      285,  286,  287,  288,  270,  271,  289,  290,  272,  274,
      275,  276,  278,  279,  280,  281,  282,  291,  292,  293,
      294,  295,  283,  296,  284,  285,  286,  287,  288,  297,
      298,  289,  290,  300,  301,  302,  303,  304,  307,  309,
      310,  311,  291,  292,  293,  294,  295,  312,  296,  313,
      314,  315,  316,  317,  297,  298,  318,  319,  300,  301,

      302,  303,  304,  307,  309,  310,  311,  321,  322,  323,
      324,  325,  312,  326,  313,  314,  315,  316,  317,  329,
      330,  318,  319,  331,  332,  333,  334,  335,  336,  337,
      338,  340,  321,  322,  323,  324,  325,  342,  326,  343,
      346,  347,  348,  349,  329,  330,  353,  328,  331,  332,
      333,  334,  335,  336,  337,  338,  340,  308,  273,  259,
      252,  246,  342,  238,  343,  346,  347,  348,  349,  352,
      352,  352,  354,  237,  354,  204,  194,  164,  151,  149,
      147,  143,  129,  118,  104,  103,   76,   70,   66,   53,
       48,   31,    9,    5,  351,  351,  351,  351,  351,  351,

      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "../run/parseParExp.l"
#line 2 "../run/parseParExp.l"
#include <string.h>
#include <string>

#include "parseParExp.tab.h"
#include "parseParDefinitions.h"

using namespace std;

#line 992 "lex.expPar.c"

#line 994 "lex.expPar.c"

#define INITIAL 0
#define RESTO_LINEA 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 13 "../run/parseParExp.l"


#line 1215 "lex.expPar.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 352 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 695 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 15 "../run/parseParExp.l"
{}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 16 "../run/parseParExp.l"
{ return EXECUTION_MODEL; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 17 "../run/parseParExp.l"
{ return CORCHETE_ABIERTO; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 18 "../run/parseParExp.l"
{ return CORCHETE_CERRADO; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 19 "../run/parseParExp.l"
{ return LLAVE_ABIERTA; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 20 "../run/parseParExp.l"
{ return LLAVE_CERRADA; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 21 "../run/parseParExp.l"
{ return REPETITIONS; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 22 "../run/parseParExp.l"
{ return NUMBER_OF_PROCESSORS; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 23 "../run/parseParExp.l"
{ return NAME_OF_EXPERIMENT; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 24 "../run/parseParExp.l"
{ return CONFIGURATIONS; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 25 "../run/parseParExp.l"
{ return INIT_PERCENT_OF_INDIVIDUALS; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 26 "../run/parseParExp.l"
{ return MIGRATION_PROBABILITY; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 27 "../run/parseParExp.l"
{ return NUMBER_OF_INDIVIDUALS_TO_MIGRATE; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 28 "../run/parseParExp.l"
{ return MAX_GLOBAL_FRONT_SIZE; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 29 "../run/parseParExp.l"
{ return MAX_FINAL_SOLUTION_SIZE; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 30 "../run/parseParExp.l"
{ return SEND_RESULTS_PER_GENERATION; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 31 "../run/parseParExp.l"
{ return SHARING; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 32 "../run/parseParExp.l"
{ return SCORE; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 33 "../run/parseParExp.l"
{ return NUMBER_PARALLEL_EXECUTIONS; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 34 "../run/parseParExp.l"
{ return MIGRATION_TOPOLOGY; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 35 "../run/parseParExp.l"
{ BEGIN RESTO_LINEA; return MIGRATION_TOPOLOGY_PARAMS; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 36 "../run/parseParExp.l"
{ return INIT_POP_ISLAND_LOADER; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 37 "../run/parseParExp.l"
{ BEGIN RESTO_LINEA; return INIT_POP_ISLAND_LOADER_PARAMS; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 38 "../run/parseParExp.l"
{ return PLUGIN_PATH; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 39 "../run/parseParExp.l"
{ BEGIN RESTO_LINEA; return CONVERSION; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 40 "../run/parseParExp.l"
{ BEGIN RESTO_LINEA; return CONVERSIONPARAMS; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 41 "../run/parseParExp.l"
{ BEGIN RESTO_LINEA; return EXECUTION_LINE; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 42 "../run/parseParExp.l"
{ BEGIN RESTO_LINEA; return MACHINEFILE; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 43 "../run/parseParExp.l"
{ BEGIN RESTO_LINEA; return PREACTION; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 44 "../run/parseParExp.l"
{ realValue = atof(yytext); return NUMERO; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 45 "../run/parseParExp.l"
{ realValue = (double) atoi(yytext); return NUMERO; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 46 "../run/parseParExp.l"
{ return DOS_PUNTOS; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 47 "../run/parseParExp.l"
{ return COMA; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 48 "../run/parseParExp.l"
{ return FLECHA; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 49 "../run/parseParExp.l"
{ stringValue = yytext; return STRING; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 50 "../run/parseParExp.l"
{ BEGIN 0; stringValue = yytext; return STRING; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 51 "../run/parseParExp.l"
{ return DOS_PUNTOS;}
	YY_BREAK
case 38:
/* rule 38 can match eol */
YY_RULE_SETUP
#line 52 "../run/parseParExp.l"
{}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 53 "../run/parseParExp.l"
ECHO;
	YY_BREAK
#line 1469 "lex.expPar.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(RESTO_LINEA):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 352 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 352 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 351);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 53 "../run/parseParExp.l"


int yywrap(){ return 1; }

